# Generated by Django 3.1.7 on 2021-03-05 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nygm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxiZoneLookup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationid', models.IntegerField(blank=True, db_column='LocationID', null=True)),
                ('borough', models.TextField(blank=True, db_column='Borough', null=True)),
                ('zone', models.TextField(blank=True, db_column='Zone', null=True)),
                ('service_zone', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'taxi_zone_lookup',
                'managed': False,
            },
        ),
    ]
