# Generated by Django 3.1.7 on 2021-03-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nygm', '0002_taxizonelookup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zonedata',
            fields=[
                ('zoneid', models.IntegerField(db_column='zoneID', primary_key=True, serialize=False)),
                ('boroughname', models.TextField(blank=True, db_column='boroughName', null=True)),
                ('zonename', models.TextField(blank=True, db_column='zoneName', null=True)),
                ('servicezone', models.TextField(blank=True, db_column='serviceZone', null=True)),
            ],
            options={
                'db_table': 'zoneData',
            },
        ),
        migrations.DeleteModel(
            name='Mapzip',
        ),
        migrations.DeleteModel(
            name='TaxiZoneLookup',
        ),
        migrations.AlterModelOptions(
            name='usertable',
            options={'managed': False},
        ),
    ]
